version: '2.1'

services:
  app:
    build: .
    links:
      - nats
      - redis
    ports:
      - "8080:8080"

  nats:
    image: nats
    ports:
      - 4222

  redis:
    image: redis
    ports:
      - 6379